
[build]
  command = "npm run build"
  publish = "dist"  # or "build" depending on your project setup

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"